import type { LevelConfig } from '../engine/types'

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Grumete',
    opLabel: '+ / −',
    operations: ['add', 'sub'],
    constraints: {
      maxA: 10,
      maxB: 10,
      allowNegativeResults: false,
      requireIntegerResults: true,
    },
    berriesPerCorrect: 10,
    xpToUnlock: 0,
  },
  {
    id: 2,
    name: 'Marinero',
    opLabel: '+ / −',
    operations: ['add', 'sub'],
    constraints: {
      maxA: 20,
      maxB: 20,
      allowNegativeResults: false,
      requireIntegerResults: true,
    },
    berriesPerCorrect: 20,
    xpToUnlock: 500,
  },
  {
    id: 3,
    name: 'Pirata',
    opLabel: '+ / − / ×2 ×5',
    operations: ['add', 'sub', 'mul'],
    constraints: {
      maxA: 100,
      maxB: 5,
      allowNegativeResults: false,
      requireIntegerResults: true,
      mulMaxB: 5,
    },
    berriesPerCorrect: 35,
    xpToUnlock: 1500,
  },
  {
    id: 4,
    name: 'Primer Oficial',
    opLabel: '× tablas',
    operations: ['mul'],
    constraints: {
      maxA: 10,
      maxB: 10,
      allowNegativeResults: false,
      requireIntegerResults: true,
    },
    berriesPerCorrect: 50,
    xpToUnlock: 3000,
  },
  {
    id: 5,
    name: 'Capitán',
    opLabel: '× / ÷',
    operations: ['mul', 'div'],
    constraints: {
      maxA: 12,
      maxB: 12,
      allowNegativeResults: false,
      requireIntegerResults: true,
    },
    berriesPerCorrect: 75,
    xpToUnlock: 6000,
  },
  {
    id: 6,
    name: 'Shichibukai',
    opLabel: '÷ resto · multi-step',
    operations: ['div', 'add', 'mul'],
    constraints: {
      maxA: 100,
      maxB: 12,
      allowNegativeResults: false,
      requireIntegerResults: false,
      multiStep: true,
    },
    berriesPerCorrect: 100,
    xpToUnlock: 12000,
  },
  {
    id: 7,
    name: 'Yonko',
    opLabel: '½ · %',
    operations: ['frac', 'pct'],
    constraints: {
      maxA: 100,
      maxB: 10,
      allowNegativeResults: false,
      requireIntegerResults: true,
      fracDenominators: [2, 4, 5, 10],
      pctValues: [10, 25, 50, 75],
    },
    berriesPerCorrect: 150,
    xpToUnlock: 25000,
  },
  {
    id: 8,
    name: 'Rey Pirata',
    opLabel: '⅔ · % · x²',
    operations: ['frac', 'pct', 'exp'],
    constraints: {
      maxA: 1000,
      maxB: 12,
      allowNegativeResults: false,
      requireIntegerResults: true,
      fracDenominators: [2, 3, 4, 5, 8, 10],
      pctValues: [10, 15, 20, 25, 30, 50, 75],
      expMax: 3,
    },
    berriesPerCorrect: 200,
    xpToUnlock: 50000,
  },
]

export const getLevelById = (id: number) => LEVELS.find(l => l.id === id)
export const getUnlockedLevels = (berries: number) => LEVELS.filter(l => l.xpToUnlock <= berries)
